GA/university-practical-exam/practical_exam/exam_scheduling/urls.py
from django.urls import path

from . import views

app_name = "exam_scheduling"
urlpatterns = [
    path("", views.index, name="index"),
    path("schedule", views.schedule, name="schedule"),
    path("display", views.display, name="display"),
]

GA/university-practical-exam/practical_exam/practical_exam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("exam_scheduling.urls")),
    path("admin/", admin.site.urls),
]

GA/university-practical-exam/practical_exam/exam_scheduling/forms.py
import datetime

import dateutil
from django import forms
from django.db.models import Max, Min
from django.http import QueryDict

from .models import College, CollegeHasDepartment, Course, Department, Teacher


class SchedulingForm(forms.Form):
    college_dept = forms.ModelChoiceField(
        queryset=CollegeHasDepartment.objects.all(),
        required=True,
        label="College and Department",
    )
    num_slots = forms.IntegerField(
        min_value=1, max_value=5, required=True, label="Number Of Slots"
    )

    # TODO: Calculate semester programmatically
    # TODO: Use enums if taking input via form
    semesters = forms.ChoiceField(
        choices=[("even", "Even"), ("odd", "Odd")], required=True, label="Semesters"
    )


class DateTimeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if "num_days" in kwargs and "num_slots" in kwargs:
            num_days = kwargs.pop("num_days")
            num_slots = kwargs.pop("num_slots")

            super().__init__(*args, **kwargs)

            today = datetime.datetime.today()
            now = datetime.datetime.combine(
                today, datetime.time(hour=datetime.datetime.now().hour)
            )

            for i in range(num_days):
                self.fields[f"day{i + 1}"] = forms.DateField(
                    initial=today,
                    required=True,
                    label=f"Day {i + 1}",
                )

            for i in range(num_slots):
                self.fields[f"slot{i + 1}_start_time"] = forms.TimeField(
                    initial=now,
                    required=True,
                    label=f"Slot {i + 1} start time",
                )
                self.fields[f"slot{i + 1}_end_time"] = forms.TimeField(
                    initial=now,
                    required=True,
                    label=f"Slot {i + 1} end time",
                )

        # Request data
        elif type(args[0]) is QueryDict:
            args = args[0]
            num_days = int(args.get("num_days"))
            num_slots = int(args.get("num_slots"))

            super().__init__(args, **kwargs)

            self.cleaned_data = {}

            for i in range(num_days):
                field_name = f"day{i + 1}"
                self.cleaned_data[field_name] = dateutil.parser.parse(
                    args.get(field_name)
                ).date()

            for i in range(num_slots):
                field_name = f"slot{i + 1}_start_time"
                self.cleaned_data[field_name] = dateutil.parser.parse(
                    args.get(field_name)
                ).time()

                field_name = f"slot{i + 1}_end_time"
                self.cleaned_data[field_name] = dateutil.parser.parse(
                    args.get(field_name)
                ).time()


class DisplayForm(forms.Form):
    choice = forms.ChoiceField(
        choices=[
            ("dep", "Department-wise"),
            ("sem", "Semester-wise"),
            ("teacher", "Teacher-wise"),
            ("seating", "Seating arrangement"),
        ],
        required=True,
    )


class CollegeDepartmentForm(forms.Form):
    college_dept = forms.ModelChoiceField(
        queryset=CollegeHasDepartment.objects.all(),
        required=True,
        label="College and Department",
    )


class CollegeDepartmentSemesterForm(forms.Form):
    college_dept = forms.ModelChoiceField(
        queryset=CollegeHasDepartment.objects.all(),
        required=True,
        label="College and Department",
    )
    semester = forms.IntegerField(
        max_value=Course.objects.aggregate(Max("semester"))["semester__max"],
        min_value=Course.objects.aggregate(Min("semester"))["semester__min"],
        required=True,
    )


class TeacherForm(forms.Form):
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all(), required=True)
    # TODO: Add college_dept to filter by college_dept


class SeatingArrangementForm(forms.Form):
    college_dept = forms.ModelChoiceField(
        queryset=CollegeHasDepartment.objects.all(),
        required=True,
        label="College and Department",
    )
    date = forms.DateField(
        initial=datetime.datetime.today(),
        required=True,
    )

GA/university-practical-exam/practical_exam/exam_scheduling/views.py
import itertools
import json
import math

from django.db import IntegrityError, transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods, require_safe

from . import utils
from .allocate import find_lab_allocations
from .forms import (
    CollegeDepartmentForm,
    CollegeDepartmentSemesterForm,
    DateTimeForm,
    DisplayForm,
    SchedulingForm,
    SeatingArrangementForm,
    TeacherForm,
)
from .models import (
    Allocation,
    College,
    CollegeHasDepartment,
    Course,
    CourseOffering,
    Department,
    Lab,
    Student,
    Teacher,
    TimeTable,
)
from .scheduling import get_res


@require_safe
def index(request):
    return render(request, "exam_scheduling/index.html")


@require_http_methods(["GET", "HEAD", "POST"])
@transaction.atomic
def schedule(request):
    if (
        request.method == "POST"
        and request.POST.get("scheduling_form", None) is not None
    ):
        scheduling_form = SchedulingForm(request.POST)

        if scheduling_form.is_valid():
            num_slots = scheduling_form.cleaned_data["num_slots"]

            sem = scheduling_form.cleaned_data["semesters"]
            semesters = semesters = Course.objects.distinct("semester").values_list(
                "semester", flat=True
            )

            if sem == "odd":
                semesters = [x for x in semesters if x % 2 == 1]
            elif sem == "even":
                semesters = [x for x in semesters if x % 2 == 0]

            courses_in_college = (
                CourseOffering.objects.filter(
                    teacher__college_dept_id=scheduling_form.cleaned_data[
                        "college_dept"
                    ]
                )
                .distinct("course__code")
                .values_list("course__code", flat=True)
            )
            courses = Course.objects.filter(
                semester__in=semesters, code__in=courses_in_college
            ).values("code", "semester")

            if len(courses) < num_slots:
                scheduling_form.add_error(
                    field=None, error="Insufficient number of courses to schedule"
                )
                return render(
                    request,
                    "exam_scheduling/schedule.html",
                    {"scheduling_form": scheduling_form},
                )

            results = get_res(1000, num_slots, courses)

            num_days = math.ceil(len(results) / num_slots)
            slot_nums = list(utils.chunks(results, num_slots))

            date_time_form = DateTimeForm(num_days=num_days, num_slots=num_slots)
            day_fields = [
                field for field in date_time_form if field.name.startswith("day")
            ]
            slot_fields = [
                field for field in date_time_form if field.name.startswith("slot")
            ]
            slot_fields = utils.chunks(slot_fields, 2)

            return render(
                request,
                "exam_scheduling/schedule.html",
                {
                    "scheduling_form": scheduling_form,
                    "college_dept": scheduling_form.cleaned_data["college_dept"].id,
                    "slots": slot_nums,
                    "num_days": num_days,
                    "num_slots": num_slots,
                    "date_time_form": date_time_form,
                    "day_fields": day_fields,
                    "slot_fields": slot_fields,
                },
            )

    elif (
        request.method == "POST"
        and request.POST.get("date_time_form", None) is not None
    ):
        date_time_form = DateTimeForm(request.POST)

        # college_dept = int(request.POST.get("college_dept"))
        college_dept = request.POST.get("college_dept")
        courses = json.loads(request.POST.get("slots").replace("'", '"'))

        try:
            with transaction.atomic():
                Allocation.objects.filter(
                    college_dept_day_slot__college_dept__exact=college_dept
                ).delete()
                TimeTable.objects.filter(college_dept__exact=college_dept).delete()

                for day_index, day in enumerate(courses):
                    for slot_index, slot in enumerate(day):
                        time_table = TimeTable(
                            college_dept=CollegeHasDepartment.objects.get(
                                id=college_dept
                            ),
                            day=day_index + 1,
                            slot=slot_index + 1,
                            course=Course.objects.get(code=slot),
                            date=date_time_form.cleaned_data[f"day{day_index + 1}"],
                            start_time=date_time_form.cleaned_data[
                                f"slot{slot_index + 1}_start_time"
                            ],
                            end_time=date_time_form.cleaned_data[
                                f"slot{slot_index + 1}_end_time"
                            ],
                        )

                        time_table.save()

        except IntegrityError as error:
            num_days = int(request.POST.get("num_days"))
            num_slots = int(request.POST.get("num_slots"))

            date_time_form.add_error(
                field=None,
                error="Failed to save timetable to database. "
                "Please enter proper date and time values.",
            )

            temp_form = DateTimeForm(num_days=num_days, num_slots=num_slots)
            day_fields = [field for field in temp_form if field.name.startswith("day")]
            slot_fields = [
                field for field in temp_form if field.name.startswith("slot")
            ]
            slot_fields = utils.chunks(slot_fields, 2)
            del temp_form

            return render(
                request,
                "exam_scheduling/schedule.html",
                {
                    "scheduling_form": SchedulingForm(),
                    "college_dept": college_dept,
                    "slots": courses,
                    "num_days": num_days,
                    "num_slots": num_slots,
                    "date_time_form": date_time_form,
                    "day_fields": day_fields,
                    "slot_fields": slot_fields,
                },
            )

        lab_allocations = find_lab_allocations(
            courses=list(itertools.chain.from_iterable(courses)),
            college_dept=college_dept,
        )
        for lab_allocation in lab_allocations:
            allocation = Allocation(
                college_dept_day_slot=TimeTable.objects.get(
                    college_dept=college_dept, course=lab_allocation["course"]
                ),
                lab=Lab.objects.get(
                    lab_id=lab_allocation["lab"], college_dept=college_dept
                ),
                int_examiner=Teacher.objects.get(id=lab_allocation["int_examiner"]),
                ext_examiner=Teacher.objects.get(id=lab_allocation["ext_examiner"]),
                start_usn=Student.objects.get(usn=lab_allocation["start_usn"]),
                end_usn=Student.objects.get(usn=lab_allocation["end_usn"]),
            )

            allocation.save()

        return redirect("exam_scheduling:display")

    else:
        return render(
            request,
            "exam_scheduling/schedule.html",
            {"scheduling_form": SchedulingForm()},
        )


@require_http_methods(["GET", "HEAD", "POST"])
def display(request):
    if request.method == "GET" or request.method == "HEAD":
        return render(
            request, "exam_scheduling/display.html", {"display_form": DisplayForm()}
        )

    # POST request
    if request.POST.get("display_form", None) is not None:
        display_form = DisplayForm(request.POST)

        if display_form.is_valid():
            if display_form.cleaned_data["choice"] == "dep":
                college_dept_form = CollegeDepartmentForm()
                return render(
                    request,
                    "exam_scheduling/display.html",
                    {
                        "display_form": display_form,
                        "college_dept_form": college_dept_form,
                    },
                )

            elif display_form.cleaned_data["choice"] == "sem":
                semester_form = CollegeDepartmentSemesterForm()
                return render(
                    request,
                    "exam_scheduling/display.html",
                    {"display_form": display_form, "semester_form": semester_form},
                )

            elif display_form.cleaned_data["choice"] == "teacher":
                teacher_form = TeacherForm()
                return render(
                    request,
                    "exam_scheduling/display.html",
                    {"display_form": display_form, "teacher_form": teacher_form},
                )

            elif display_form.cleaned_data["choice"] == "seating":
                seating_form = SeatingArrangementForm()
                return render(
                    request,
                    "exam_scheduling/display.html",
                    {"display_form": display_form, "seating_form": seating_form},
                )

    elif request.POST.get("college_dept_form", None) is not None:
        college_dept_form = CollegeDepartmentForm(request.POST)

        if college_dept_form.is_valid():
            college_dept = college_dept_form.cleaned_data["college_dept"]

            dates = (
                TimeTable.objects.filter(college_dept__exact=college_dept)
                .distinct("day")
                .order_by("day")
                .values_list("date", flat=True)
            )

            if not dates:
                college_dept_form.add_error(

GA/university-practical-exam/practical_exam/exam_scheduling/templates/exam_scheduling/display.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load exam_scheduling_extras %}

{% block title %}View Generated Timetable{% endblock %}

{% block heading %}View Generated Timetable{% endblock %}

{% block content %}
<div class="mt-10 sm:mt-0 pt-4 sm:pt-2">
  <div class="md:grid md:grid-cols-2 md:gap-6 mt-4">
    {{ display_form.non_field_errors }}

    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:display' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-4 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ display_form.choice.errors }}
                {{ display_form.choice.label_tag }}
                {{ display_form.choice|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="display_form">
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="hidden sm:block" aria-hidden="true">
    <div class="py-5">
      <div class="border-t border-gray-200"></div>
    </div>
  </div>

  {% if college_dept_form %}
  <div class="md:grid md:grid-cols-2 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:display' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-4 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ college_dept_form.college_dept.errors }}
                {{ college_dept_form.college_dept.label_tag }}
                {{ college_dept_form.college_dept|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="college_dept_form">
                  Submit
                </button>
              </div>
            </div>

            {{ college_dept_form.non_field_errors }}
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}

  {% if semester_form %}
  <div class="md:grid md:grid-cols-2 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:display' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-5 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ semester_form.college_dept.errors }}
                {{ semester_form.college_dept.label_tag }}
                {{ semester_form.college_dept|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 sm:col-span-1">
                {{ semester_form.semester.errors }}
                {{ semester_form.semester.label_tag }}
                {{ semester_form.semester|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="semester_form">
                  Submit
                </button>
              </div>
            </div>

            {{ semester_form.non_field_errors }}
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}

  {% if teacher_form %}
  <div class="md:grid md:grid-cols-2 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:display' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-4 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ teacher_form.teacher.errors }}
                {{ teacher_form.teacher.label_tag }}
                {{ teacher_form.teacher|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="teacher_form">
                  Submit
                </button>
              </div>
            </div>

            {{ teacher_form.non_field_errors }}
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}

  {% if seating_form %}
  <div class="md:grid md:grid-cols-2 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:display' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ seating_form.college_dept.errors }}
                {{ seating_form.college_dept.label_tag }}
                {{ seating_form.college_dept|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-2 sm:col-span-2">
                {{ seating_form.date.errors }}
                {{ seating_form.date.label_tag }}
                {{ seating_form.date|attr:"type:date"|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="seating_form">
                  Submit
                </button>
              </div>
            </div>

            {{ seating_form.non_field_errors }}
          </div>
        </div>
      </form>
    </div>
  </div>
  {% endif %}

  {% if college_dept_form or semester_form or teacher_form or seating_form %}
  <div class="hidden sm:block" aria-hidden="true">
    <div class="py-5">
      <div class="border-t border-gray-200"></div>
    </div>
  </div>
  {% endif %}

  {% if courses %}
  <div class="flex flex-col w-10/12 m-auto py-4">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-300 sm:rounded-lg bg-white">
          <table>
            <thead>
              <tr>
                <th scope="col"></th>

                {% for time in times %}
                <th scope="col">{{ time.start_time }} - {{ time.end_time }}</th>
                {% endfor %}
              </tr>
            </thead>
            <tbody>
              {% for date, course_list in dates|zip:courses %}
              <tr>
                <th scope="row">{{ date }}</th>

                {% for course in course_list %}
                <td>{{ course }}</td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if courses_colleges_labs %}
  <div class="flex flex-col w-10/12 m-auto py-4">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-300 sm:rounded-lg bg-white">
          <table>
            <thead>
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Course</th>
                <th scope="col">Time</th>
              </tr>
            </thead>
            <tbody>
              {% for date, course_college_lab in dates|zip:courses_colleges_labs %}
              <tr>
                {% comment %} {% for course_college_lab, time in course_college_lab_list|zip:times %} {% endcomment %}
                <td>{{ date }}</td>
                <td>
                  <div class="text-sm text-gray-700">
                    {{ course_college_lab.course }}
                  </div>
                  {% if course_college_lab.course and course_college_lab.course.strip %}
                  <div class="text-sm text-gray-500">
                    {{ course_college_lab.college }} - {{ course_college_lab.lab }}
                  </div>
                  {% endif %}
                </td>
                <td>{{ course_college_lab.time.start_time }} - {{ course_college_lab.time.end_time }}</td>
                {% comment %} {% endfor %} {% endcomment %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% if courses_labs_usns %}
  <div class="flex flex-col w-6/12 m-auto py-4">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-300 sm:rounded-lg bg-white">
          <table>
            <thead>
              <tr>
                <th scope="col">Course</th>
                <th scope="col">Lab</th>
                <th scope="col">USN</th>
              </tr>
            </thead>
            <tbody>
              {% for course_lab_usn in courses_labs_usns %}
              <tr>
                <th scope="row">{{ course_lab_usn.course }}</th>

                <td>{{ course_lab_usn.lab }}</td>
                <td>{{ course_lab_usn.start_usn }} - {{ course_lab_usn.end_usn }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

</div>
{% endblock content %}

GA/university-practical-exam/practical_exam/exam_scheduling/templates/exam_scheduling/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block heading %}Exam Scheduling{% endblock %}

{% block content %}
Hello, there!
{% endblock content %}

GA/university-practical-exam/practical_exam/exam_scheduling/templates/exam_scheduling/schedule.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Exam Scheduling{% endblock %}

{% block heading %}Schedule{% endblock %}

{% block content %}
<div class="mt-10 sm:mt-0 pt-4 sm:pt-2">
  <div class="md:grid md:grid-cols-2 md:gap-6 mt-4">
    <div class="mt-5 md:mt-0 md:col-span-2 mx-auto">
      <form action="{% url 'exam_scheduling:schedule' %}" method="POST">
        {% csrf_token %}

        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-8 gap-6">
              <div class="col-span-4 sm:col-span-3">
                {{ scheduling_form.college_dept.errors }}
                {{ scheduling_form.college_dept.label_tag }}
                {{ scheduling_form.college_dept|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-2 sm:col-span-2">
                {{ scheduling_form.num_slots.errors }}
                {{ scheduling_form.num_slots.label_tag }}
                {{ scheduling_form.num_slots|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-2 sm:col-span-2">
                {{ scheduling_form.semesters.errors }}
                {{ scheduling_form.semesters.label_tag }}
                {{ scheduling_form.semesters|add_error_attr:"aria-invalid:true" }}
              </div>

              <div class="col-span-1 mt-auto mx-auto">
                <button type="submit" name="scheduling_form">
                  Submit
                </button>
              </div>
            </div>

            {{ scheduling_form.non_field_errors }}
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="hidden sm:block" aria-hidden="true">
    <div class="py-5">
      <div class="border-t border-gray-200"></div>
    </div>
  </div>

  {% if slots %}
  <div class="flex flex-col w-10/12 m-auto py-4">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-300 sm:rounded-lg bg-white">
          <table>
            <thead>
              <tr>
                <th scope="col"></th>

                {% for _ in slots.0 %}
                <th scope="col">Slot {{ forloop.counter }}</th>
                {% endfor %}
              </tr>
            </thead>
            <tbody>
              {% for day in slots %}
              <tr>
                <th scope="row">Day {{ forloop.counter }}</th>

                {% for subject in day %}
                <td>{{ subject }}</td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="flex flex-col w-10/12 m-auto py-4 content-center justify-center items-center">
    <form action="{% url 'exam_scheduling:schedule' %}" method="POST">
      {% csrf_token %}

      <input name="slots" type="hidden" value="{{ slots }}">
      <input name="num_days" type="hidden" value="{{ num_days }}">
      <input name="num_slots" type="hidden" value="{{ num_slots }}">
      <input name="college_dept" type="hidden" value="{{ college_dept }}">

      <div class="shadow overflow-hidden sm:rounded-md max-w-max">
        <div class="px-4 py-5 bg-white sm:p-6">
          <div class="flex flex-col content-center justify-center">
            <div class="flex flex-row self-center content-center justify-center">
              <div class="flex flex-col px-4">
                {% for field in day_fields %}
                <div class="py-2">
                  {{ field.errors }}
                  {{ field.label_tag }}
                  {{ field|attr:"type:date"|add_error_attr:"aria-invalid:true" }}
                </div>
                {% endfor %}
              </div>

              <div class="flex flex-col px-4">
                {% for start_end_pair in slot_fields %}
                <div class="flex flex-row py-2">
                  {% for field in start_end_pair %}
                  <div class="px-2">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field|attr:"type:time"|attr:"step:60"|add_error_attr:"aria-invalid:true" }}
                  </div>
                  {% endfor %}
                </div>
                {% endfor %}
              </div>
            </div>

            <div class="mt-5 self-center mx-auto">
              <button type="submit" name="date_time_form">
                Submit
              </button>
            </div>
          </div>

          {{ date_time_form.non_field_errors }}
        </div>
    </form>
  </div>

  {% endif %}
</div>
{% endblock content %}